### ISSUE TITLE
Stop adding menu items everywhere

### ISSUE THREAD

**Issue by RichardLuo0** [vizzuhq/codeviz#14]
First of all, thank you for bringing up such a fantastic extension. However, your extension is adding entries to every menu. It is really annoying that this appears everywhere and I have no idea how to turn it off. I think simply making it a command I can call from the command palette will be sufficient.
![image](https://user-images.githubusercontent.com/22096448/197994689-96fb0d76-bc60-4a46-b42d-6c034d462907.png)
![image](https://user-images.githubusercontent.com/22096448/197994849-2f6e74c7-8546-4206-935f-e699fa3590c6.png)
![image](https://user-images.githubusercontent.com/22096448/197995100-b0062a54-5bcf-4984-b265-b036b887c1de.png)
![image](https://user-images.githubusercontent.com/22096448/197995375-5dd070ba-aecc-4b88-bccc-9b93890e6a94.png)

**Comment by simzer** [comment]
Hi, thanks for reporting this. This is a bug, we only intended to put it into a single menu in the explorer tab.

**Comment by tczagany** [comment]
The mentioned menu item has been moved to the explorer's context menu.
